### ISSUE TITLE
[BUG] DynamicData.ReactiveUI causes Release compilation failures while having a reference to ReactiveUI 10.0.1 or later

### ISSUE THREAD

**Issue by AkilaeTribe** [reactiveui/DynamicData#295]
**Describe the bug**

Attempting to use the latest version of DynamicData.ReactiveUI package (6.11.0.2613) and ReactiveUI (10.0.1 or later) causes a failure 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'ReactiveUI.Legacy.IReadOnlyReactiveList`1' (defined in assembly 'DynamicData.ReactiveUI, Version=6.11.0.2613, Culture=neutral, PublicKeyToken=null') with scope 'ReactiveUI, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve ReactiveUI.Legacy.IReadOnlyReactiveList`1
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance)
   at Mono.Linker.Steps.MarkStep.GetOriginalType(TypeReference type)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeFields(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	LinkAssembliesFailure.Android			
```

**Steps To Reproduce**

[LinkAssembliesFailure.zip](https://github.com/reactiveui/DynamicData/files/3776261/LinkAssembliesFailure.zip)

1. Create a new Xamarin.Forms project using Visual Studio 2019.
2. Add reference to ReactiveUI latest version (10.0.1+).
3. Add reference to DynamicData.ReactiveUI latest version (6.11.0.2613).
4. (Optional) Update all packages used by the projects to their latest version.
5. Set the solution configuration to Release and build the application.

**Expected behavior**

I expect a successful build when latest versions of ReactiveUI and DynamicData.ReactiveUI packages are referenced.

**Environment**

- OS:       Windows 8.1
Visual Studio 2019

**Additional context**

The issue could be related to the removal of ReactiveUI.Legacy.IReadOnlyReactiveList. See [ReactiveUI Release 10.0](https://github.com/reactiveui/ReactiveUI/commit/f396c32159999686831c2801d4b7c4a538fd54a3#diff-7a5e30151788f398a5900daa0b5f912a).

For some reason, the application can be built in Debug mode.

**Comment by glennawatson** [comment]
DynamicData.ReactiveUI is deprecated. It only existed to support ReactiveList which was removed in 10.

**Comment by AkilaeTribe** [comment]
If DynamicData.ReactiveUI is deprecated, I assume the correct move is to remove that dependency.

I tried that, and the build is successful, in both Debug and Release modes. Thank you for your assistance !
