### ISSUE TITLE
[BUG] InvalidOperationException from InnerJoin

### ISSUE THREAD

**Issue by John-MartinMalone** [reactiveui/DynamicData#364]
The implementation of InnerJoin seems not completely thread safe and sometimes gives an InvalidOperationException with the message "Collection was modified; enumeration operation may not execute."

Stack Trace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary\`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator\`2.MoveNext()
   at System.Collections.Generic.List\`1..ctor(IEnumerable\`1 collection)
   at DynamicData.Cache.Internal.CacheEx.GetInitialUpdates[TObject,TKey](ChangeAwareCache\`2 source, Func\`2 filter)
   at DynamicData.Cache.Internal.LockFreeObservableCache\`2.<>c__DisplayClass9_0.<Connect>b__0()
   at System.Reactive.Linq.ObservableImpl.Defer\`1._.Run()
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver\`1.OnError(Exception error)
   at System.Reactive.Sink\`1.ForwardOnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Defer\`1._.Run()
   at System.Reactive.Linq.ObservableImpl.Defer\`1.Run(_ sink)
   at System.Reactive.Producer\`2.SubscribeRaw(IObserver\`1 observer, Boolean enableSafeguard)
   at System.Reactive.Producer\`2.Subscribe(IObserver\`1 observer)
   at System.ObservableExtensions.Subscribe[T](IObservable\`1 source, Action\`1 onNext)
   at DynamicData.Cache.Internal.InnerJoin\`5.<Run>b__5_0(IObserver\`1 observer)
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable\`1.SubscribeCore(IObserver\`1 observer)
   at System.Reactive.ObservableBase\`1.ScheduledSubscribe(AutoDetachObserver\`1 autoDetachObserver)

InnerJoin creates a LockFreeObservableCache and calls Connect on that.
Connect calls GetInitialUpdates(), which iterates the Dictionary backing the cache, while another thread may be making changes to the collection

The following code demonstrates the problem (but not every time):

```
class Thing
{
    public long Id { get; set; }
    public string Name { get; set; }    
}

void Main()
{
    var ids = ObservableChangeSet.Create<long, long>(sourceCache => Observable.Range(1,1000000, Scheduler.Default).Subscribe(x => sourceCache.AddOrUpdate(x)), x => x);
    
    var itemsCache = new SourceCache<Thing,long>(x => x.Id);
    itemsCache.AddOrUpdate(new[]
    {
        new Thing {Id = 300, Name = "Quick"},
        new Thing {Id = 600, Name = "Brown"},
        new Thing {Id = 900, Name = "Fox"},
        new Thing {Id = 1200, Name = "Hello"},
    });

    ids.InnerJoin(itemsCache.Connect(), x => x.Id, (_, thing) => thing)
        .Subscribe();
}
```

**Environment**

- OS:       Windows 10
- Device:   PC
- Version:   6.14.18

**Comment by bddckr** [comment]
I just saw this pop up in the latest release. The PR descriptions says

>If this fix works as expected, the same changes should be applied to all the join operations

Is there an issue I can follow for that additional work or has it perhaps been done already (and no changes have been necessary)?


Thanks for the hard work!

**Comment by RolandPheasant** [comment]
There has been no issue raised for the other join operators yet. However it stands to reason that the same issue exists in all the other join operators.  My rational with applying the fix in one place first it so you can verify the fix. Can you please use the latest package and feed back whether the issue has gone away.

The fix was very simple. If you follow the linked PR, I changed an overload which applies a stricter locking model.

> Thanks for the hard work!

Much appreciated

**Comment by bddckr** [comment]
I've been personally getting the `InvalidOperationException` on `InnerJoin` very rarely in our app, and was unable to reduce it down to a minimum repro yet.

However, the repro provided by @John-MartinMalone above does fail for me on 6.14.18 nine out of ten times. Updating to 6.14.20 and I'm now unable to reproduce the issue!
(I've been running this repro on both .NET Core SDK 3.1.300, as well as Xamarin.Android SDK 10.3.1.4 on device.)
